import { describe, expect, it } from "vitest";
import { candidateSlug as sitemapSlug } from "../../../scripts/generate-sitemap.mjs";
import { candidateSlug, legacyCandidateSlug } from "./format";

// The sitemap is generated by a plain Node script with its own copy of the
// slug function; a drift would publish candidate URLs that 404.
const NAMES = [
  "Jane Doe",
  "José Peña",
  "Zoë Lofgren",
  "Søren Kierkegaard",
  "Đorđe Novak",
  "Ægir Æsir",
  "Łukasz Błaszczykowski",
  "Hans Großmann",
  "Œuvre Cœur",
  "Þór Guðmundsson",
  "Ayşe Kılıç",
  "Nguyễn Văn Đức",
  "O'Brien-Smith Jr.",
  "  Leading and trailing  ",
  "李明",
  "!!!",
  "",
  "Mary-Jane Watson III",
  "Renée Élise Müller",
];

describe("sitemap candidate slug parity", () => {
  it.each(NAMES)("matches candidateSlug for %j", (name) => {
    expect(sitemapSlug(name)).toBe(candidateSlug(name));
  });

  it("folds letters that Unicode decomposition leaves alone", () => {
    expect(candidateSlug("Søren Łukasz")).toBe("soren-lukasz");
    expect(candidateSlug("Đorđe")).toBe("dorde");
    expect(candidateSlug("Ægir Großmann")).toBe("aegir-grossmann");
    expect(candidateSlug("Cœur")).toBe("coeur");
  });

  it("leaves the legacy slug scheme unchanged", () => {
    expect(legacyCandidateSlug("Søren Łukasz")).toBe("s-ren-ukasz");
    expect(legacyCandidateSlug("José Peña")).toBe("jos-pe-a");
  });
});
